"""empty message

Revision ID: facee0195fd1
Revises: 
Create Date: 2020-08-16 17:21:47.828859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'facee0195fd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('st_student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('English', sa.Float(precision=20), nullable=False),
    sa.Column('Python', sa.Float(precision=20), nullable=False),
    sa.Column('C', sa.Float(precision=20), nullable=False),
    sa.Column('Grade_num', sa.Float(precision=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('st_student')
    # ### end Alembic commands ###
